---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-instances
  namespace: cluster-main-observability
  labels:
    app.kubernetes.io/name: cnpg-instances
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: monitoring
    entity: cluster
    env: main
    capability: observability
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
