---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: human-operator
  namespace: flux-system
  labels:
    app.kubernetes.io/name: human-operator
    app.kubernetes.io/part-of: basis
    app.kubernetes.io/component: operator-identity
    entity: cluster
    capability: access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: human-operator
  labels:
    app.kubernetes.io/name: human-operator
    app.kubernetes.io/part-of: basis
    app.kubernetes.io/component: operator-identity
    entity: cluster
    capability: access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: human-operator
  labels:
    app.kubernetes.io/name: human-operator
    app.kubernetes.io/part-of: basis
    app.kubernetes.io/component: operator-identity
    entity: cluster
    capability: access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: human-operator
subjects:
  - kind: ServiceAccount
    name: human-operator
    namespace: flux-system
