apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cf-providers.yaml
  - cf-runtime.yaml
  - gcp-providers.yaml
  - gcp-runtime.yaml
  - human-operator.yaml
  - logs-api.yaml
  - logs-pg.yaml
  - mcp-flux.yaml
  - policies.cleanup.yaml
  - policies.secrets.yaml
