apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jobs.yaml
nameSuffix: -v1-32
configMapGenerator:
  - name: node-update-step
    namespace: kured
    literals:
      - expected-digest=sha256:60a4a35e75f408e6b0e60fb7f0eb8f6a931a6e82d831ee21ea8601d8290bf984
