apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jobs.yaml
nameSuffix: -v1-33
configMapGenerator:
  - name: node-update-step
    namespace: kured
    literals:
      - expected-digest=sha256:11682b623e056664f64f430cb19e6dda844ba3ecb0f20f5ef4ea7e42e8ab21af
