apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jobs.yaml
nameSuffix: -v1-34
configMapGenerator:
  - name: node-update-step
    namespace: kured
    literals:
      - expected-digest=sha256:059d112a714ffc3822c02bc1cdfc4e0566ac16dc04d1092bb642b2440214034a
