---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  cluster:
    domain: k.famevans.win
    multitenant: false
    networkPolicy: true
    type: kubernetes
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  distribution:
    registry: ghcr.io/fluxcd
    version: 2.x
