---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  cluster:
    domain: k.famevans.win
    multitenant: false
    networkPolicy: true
    type: kubernetes
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  distribution:
    registry: ghcr.io/fluxcd
    version: 2.7.2
  kustomize:
    patches:
      - target:
          kind: Deployment
          name: kustomize-controller
        patch: |
          - op: test
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=info
          - op: replace
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=error

      - target:
          kind: Deployment
          name: source-controller
        patch: |
          - op: test
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=info
          - op: replace
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=error

      - target:
          kind: Deployment
          name: helm-controller
        patch: |
          - op: test
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=info
          - op: replace
            path: /spec/template/spec/containers/0/args/2
            value: --log-level=error

      - target:
          kind: Deployment
          name: notification-controller
        patch: |
          - op: test
            path: /spec/template/spec/containers/0/args/1
            value: --log-level=info
          - op: replace
            path: /spec/template/spec/containers/0/args/1
            value: --log-level=error
