apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-instance.yaml
  - ns.yaml
  - helmrepos.yaml
  - controllers.yaml
  - probe-etcd-version-k-0ad0ff18.yaml
  - probe-etcd-version-k-95509ca9.yaml
  - probe-etcd-version-k-e7488b70.yaml
